name: input Multiple jobs
on:
 workflow_dispatch:
  inputs:
    runner:
      description: "Select the runner"
      required: true 
      type: choice
      options:
        - ubuntu-latest
        - ubuntu-22.04
        - self-hosted
        - windows-latest
    job-name:
      description: "Enter the multiple jobs to run"
      type: string
jobs:
  buildjob:
    if: contains(github.event.inputs.jobs-name, 'buildjob')
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "build the code"
  testjob:
    if: contains(github.event.inputs.jobs-name, 'testjob')
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "test the code on runner."
  deployjob:
    if: contains(github.event.inputs.jobs-name, 'deployjob')
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "deploy the code on runner."
