name: Multiple runners and chosse jobs
on:
 workflow_dispatch:
  inputs:
    runner:
      description: "Select the runner"
      required: true 
      type: choice
      options:
        - ubuntu-latest
        - ubuntu-22.04
        - self-hosted
        - windows-latest
    job-name:
      description: "select the job to runner"
      required: true 
      type: choice 
      options:
        - buildjob
        - testjob
        - deployjob
    # job-name:
    #.  description: "Enter the multiple jobs to run"
    #.  type: string
    #.  when running the job, we will give job names seprated by comma  
jobs:
  buildjob:
    if: ${{ github.event.inputs.jobs-name}}
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "build the code"
  testjob:
    if: ${{ github.event.inputs.jobs-name}}
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "test the code on runner."
  deployjob:
    if: ${{ github.event.inputs.jobs-name}}
    runs-on: ${{ github.event.inputs.runner}}
    steps:
    - name: build code
      run: echo "deploy the code on runner."
